name: build unix

on:
  push:
    # branches: [ "main" ]
    # tags: ["v*"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          make

      - name: Strip binary
        run: |
          strip gipool || true

      - name: Rename output
        run: |
          OS_NAME=$(uname | tr '[:upper:]' '[:lower:]')
          mv gipool gipool_${OS_NAME}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gipool-${{ matrix.os }}
          path: gipool_*

      - name: Prepare release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          OS_NAME=$(uname | tr '[:upper:]' '[:lower:]')
          mv gipool_${OS_NAME} gipool_${{ github.ref_name }}_${OS_NAME}

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: gipool_${{ github.ref_name }}_*
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
